layout_spectrum: 0.5019981
typography_spectrum: 0.1298695
color:
  saturation: 0.7989894
  lightness: 0.1263594
  brandStrength: 0.01662617
  rhythmicContrast: 0.5793356
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Damien Pascoe
